---

- name: Create configuration file
  ansible.builtin.template:
    src: "project_properties.conf.j2"
    dest: "{{ steamengine_conf_path }}/project_env.conf"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rw,g=r,o=
  when: steamengine_project_configuration is defined
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_play2

- name: Create external configuration file
  ansible.builtin.template:
    src: "{{ steamengine_project_configuration_template_path }}"
    dest: "{{ steamengine_conf_path }}/project_env.conf"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rw,g=r,o=
  when: steamengine_project_configuration_template_path is defined
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_play2

- name: "Download build {{ steamengine_build_url }}"
  ansible.builtin.get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ checksum_verified }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rwx,g=rx,o=
    headers: "{{ steamengine_build_url_headers }}"
    validate_certs: "{{ steamengine_build_url_validate_certs }}"
  notify:
    - "{{ steamengine_project_name }} restart"
  register: get_url_build
  tags:
    - steamengine_deploy_play2

- name: "Is there a new build: {{ get_url_build.changed }}"
  ansible.builtin.set_fact:
    new_build_to_deploy: "{{ get_url_build.changed }}"
  tags:
    - steamengine_deploy_play2

- include_tasks:
    file: common/pre_deploy.yml
    apply:
      tags:
        - steamengine_deploy_play2
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: Create tmp directory
  ansible.builtin.tempfile:
    state: directory
    suffix: "{{ steamengine_project_name }}"
  register: tempdir
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: Unarchive build
  ansible.builtin.unarchive:
    src: "{{ steamengine_project_root_path }}/project.zip"
    dest: "{{ tempdir.path }}"
    remote_src: true
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: Clean www directory
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    state: absent
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: Clean www directory (2)
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rwx,g=rx,o=
    state: directory
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: "Move archive files to {{ steamengine_project_root_path_web }}"
  ansible.builtin.shell: "mv {{ tempdir.path }}/*/* {{ steamengine_project_root_path_web }}"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: "Recursively change ownership of {{ steamengine_project_root_path_web }}"
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    state: directory
    recurse: true
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rwx,g=rx,o=
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: Remove tmp directory
  ansible.builtin.file:
    path: "{{ tempdir.path }}"
    state: absent
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: Move start_project script
  ansible.builtin.shell: |
    shopt -s extglob
    mv {{ steamengine_project_root_path_web }}/bin/!(*.bat) {{ steamengine_project_root_path_web }}/bin/{{ steamengine_play2_run_script }}
  args:
    executable: /bin/bash
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2

- name: Make script executable
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}/bin/{{ steamengine_play2_run_script }}"
    state: file
    mode: u=rwx,g=rx,o=x
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_play2
