---

- name: Create project folder structure (5)
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: 0750
  with_items:
    - "{{ steamengine_sf_external_logs_path }}"
  tags:
    - steamengine_deploy_sf

- name: Create project folder structure (6)
  ansible.builtin.file:
    path: "{{ steamengine_persistent_base_path }}/{{ item.path }}"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: 0770
  with_items: "{{ steamengine_persistent_directories }}"
  tags:
    - steamengine_deploy_sf

- name: Create configuration file
  ansible.builtin.template:
    src: "project_properties.env.j2"
    dest: "{{ steamengine_conf_path }}/.env.local"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rw,g=r,o=
  when: steamengine_project_configuration is defined
  tags:
    - steamengine_deploy_sf

- name: Ensure custom configuration directory exists
  ansible.builtin.file:
    path: "{{ steamengine_conf_path }}/{{ item.value | dirname }}"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: 0770
  with_dict: "{{ steamengine_sf_project_custom_configurations_template_path }}"
  tags:
    - steamengine_deploy_sf

- name: "Download build {{ steamengine_build_url }}"
  ansible.builtin.get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ checksum_verified }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rwx,g=rx,o=
    headers: "{{ steamengine_build_url_headers }}"
    validate_certs: "{{ steamengine_build_url_validate_certs }}"
  notify:
    - "{{ steamengine_project_name }} fixpermissions"
  register: get_url_build
  tags:
    - steamengine_deploy_sf

- name: "Is there a new build: {{ get_url_build.changed }}"
  ansible.builtin.set_fact:
    new_build_to_deploy: "{{ get_url_build.changed }}"
  tags:
    - steamengine_deploy_sf

- include_tasks:
    file: common/pre_deploy.yml
    apply:
      tags:
        - steamengine_deploy_sf
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: Create custom configuration file
  ansible.builtin.template:
    src: "{{ item.key }}"
    dest: "{{ steamengine_conf_path }}/{{ item.value }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rw,g=r,o=
  with_dict: "{{ steamengine_sf_project_custom_configurations_template_path }}"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: Create tmp directory
  ansible.builtin.tempfile:
    state: directory
    suffix: "{{ steamengine_project_name }}"
  register: tempdir
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: Unarchive build
  ansible.builtin.unarchive:
    src: "{{ steamengine_project_root_path }}/project.zip"
    dest: "{{ tempdir.path }}"
    remote_src: true
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: Check www directory exists
  ansible.builtin.stat:
    path: "{{ steamengine_project_root_path_web }}"
  register: root_path_web_directory
  tags:
    - steamengine_deploy_sf

- name: Fix permissions before updating source
  ansible.builtin.command: "/{{ steamengine_project_name }}/bin/steamengine fixpermissions"
  when: new_build_to_deploy and root_path_web_directory.stat.exists
  tags:
    - steamengine_deploy_sf

- name: Clean www directory
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    state: absent
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: "Move archive files to {{ steamengine_project_root_path_web }}"
  ansible.builtin.command: "mv {{ tempdir.path }} {{ steamengine_project_root_path_web }}"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: "Add read permission for {{ steamengine_project_user }}"
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    recurse: true
    mode: u=rwx,g=rx,o=
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: "Ensure var directory exists"
  ansible.builtin.file:
    path: "{{ steamengine_sf_var_path }}"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: 0750
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: Create configuration link
  ansible.builtin.file:
    state: link
    src: "{{ steamengine_conf_path }}/.env.local"
    dest: "{{ steamengine_project_root_path_web }}/.env.local"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
  when: new_build_to_deploy and steamengine_project_configuration is defined
  tags:
    - steamengine_deploy_sf

- name: Create custom configuration link
  ansible.builtin.file:
    state: link
    src: "{{ steamengine_conf_path }}/{{ item.value }}"
    dest: "{{ steamengine_project_root_path_web }}/{{ item.value }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
  with_dict: "{{ steamengine_sf_project_custom_configurations_template_path }}"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: Clean logs link directory
  ansible.builtin.file:
    state: absent
    path: "{{ steamengine_sf_log_path }}"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: Create logs link directory
  ansible.builtin.file:
    state: link
    src: "{{ steamengine_sf_external_logs_path }}"
    dest: "{{ steamengine_sf_log_path }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf

- name: "Ensure path with write permission exists"
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}/{{ item }}"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_project_user }}"
    mode: u=rwx,g=rwx,o=
  with_items: "{{ steamengine_sf_path_with_write_permission }}"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_sf
