---
language: python
python:
  - "2.7"
services:
  - docker
env:
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu-18.04
install:
  - pip install -r requirements.txt
script:
  - molecule --version
  - ansible --version
  - molecule test --all