---

- name: Verify project type
  ansible.builtin.assert:
    that:
      - "steamengine_project_type is defined"
      - "steamengine_project_type in steamengine_project_types"
  tags: always

- name: "Include variables for {{ steamengine_project_type }}"
  ansible.builtin.include_vars:
    file: "vars/{{ steamengine_project_type }}.yml"
  tags: always

- include_tasks:
    file: "{{ steamengine_project_type }}/asserts.yml"
    apply:
      tags:
        - steamengine_deploy
  tags: always

- include_tasks:
    file: common/install_deps.yml
    apply:
      tags:
        - steamengine_dependencies
  tags: always

- include_tasks:
    file: common/user.yml
    apply:
      tags:
        - steamengine_user
  tags: always

- include_tasks:
    file: common/structure.yml
    apply:
      tags:
        - steamengine_structure
  tags: always

- include_tasks:
    file: common/runtime.yml
    apply:
      tags:
        - steamengine_runtime
  tags: always

- include_tasks:
    file: "{{ steamengine_project_type }}/runtime.yml"
    apply:
      tags:
        - steamengine_runtime
  tags: always

- name: "Initialize var new_build_to_deploy"
  ansible.builtin.set_fact:
    new_build_to_deploy: false
  tags: always

- include_tasks:
    file: "{{ steamengine_project_type }}/deploy.yml"
    apply:
      tags:
        - steamengine_deploy
  when: steamengine_build_url is defined and steamengine_build_url
  tags: always

- include_tasks:
    file: common/cron.yml
    apply:
      tags:
        - steamengine_cron
  tags: always

- include_tasks:
    file: common/post_deploy.yml
    apply:
      tags:
        - steamengine_deploy
  tags: always

- include_tasks:
    file: common/delete_project.yml
    apply:
      tags:
        - steamengine_delete_project
  when: steamengine_delete_project