---

- name: Verify build extension
  ansible.builtin.assert:
    that: (steamengine_build_url | basename | splitext)[1] == ".zip"
  when: steamengine_build_url is defined and steamengine_build_url
  tags:
    - steamengine_deploy_drupal

- name: Verify db dump extension
  ansible.builtin.assert:
    that:
      - (steamengine_drupal_db_dump_url | basename | splitext)[-1] == ".zip"
  when: steamengine_drupal_db_dump_url is defined and steamengine_drupal_db_dump_url
  tags:
    - steamengine_deploy_drupal
