---
- name: Converge
  hosts: instance
  become: true

  pre_tasks:
    - include_tasks: "../resources/setup_{{ ansible_os_family | lower }}.yml"

  roles:
    - role: lean_delivery.java
      vars:
        java_distribution: adoptopenjdk
        transport: adoptopenjdk-fallback
        java_major_version: 8
        java_minor_version: 222
        adoptopenjdk_impl: openj9
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        steamengine_project_name: test_tomcat7
        steamengine_project_type: tomcat7
        steamengine_build_url: https://delivery.steamulo.org/SteamEngineV2_tests/tomcat_test.war
        steamengine_build_checksum: sha1:80f5053b166c69d81697ba21113c673f8372aca0..
        steamengine_tomcat7_http_port: 8088
        steamengine_project_configuration:
          test_conf:
            item1: test1
            item2:
              item2_sub1: test2
              item2_sub2: test3
