---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length:
        max: 120
platforms:
  - name: instance
    image: leandelivery/docker-systemd:${MOLECULE_DISTRO:-ubuntu-18.04}
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["503", "204"]
scenario:
  name: static
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
