---

- name: "Download build {{ steamengine_build_url }}"
  get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ steamengine_build_checksum }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  register: get_url_build
  tags:
    - steamengine_deploy_static

- name: Create www directory
  file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    state: directory
  tags:
    - steamengine_deploy_static

- name: Update www directory
  include_tasks: include/update_from_archive.yml
  vars:
    archive_path: "{{ steamengine_project_root_path }}/project.zip"
    dest_path: "{{ steamengine_project_root_path_web }}"
  when: get_url_build.changed
  args:
    apply:
      tags:
        - steamengine_deploy
        - steamengine_deploy_static
  tags:
    - steamengine_deploy_static

- name: "Add read permission for {{ steamengine_app_user }}"
  file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    recurse: true
    mode: u=rwx,g=rx,o=
  tags:
    - steamengine_deploy_static
