---

- name: Delete project
  ansible.builtin.group:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ steamengine_project_user }}"
    - "{{ steamengine_app_user }}"


- name: Delete directories if exists
  ansible.builtin.file:
    state: absent
    path: "/{{ steamengine_project_name }}/{{ item.symlink_src }}"
  when:
    - item.delete_dir is defined and item.delete_dir
  loop: "{{ steamengine_persistent_directories }}"

- name: Delete services currently running
  ansible.builtin.systemd:
    enabled: false
    daemon_reload: true
    name: "{{ steamengine_project_name }}-{{ item.name }}"
  loop: "{{ steamengine_extra_services }}"

- name: Remove systemd unit file
  ansible.builtin.file:
  file:
    path: "/etc/systemd/system/{{ steamengine_project_name }}.service"
    state: absent
  become: true

- name: Remove service files
  file:
    path: "{{ service_path }}"
    state: absent
    recurse: yes
  become: true

- name: "Delete user {{ steamengine_project_user }}"
  ansible.builtin.user:
    name: "{{ steamengine_project_user }}"
    state: absent


- name: "Uninstall all associated packages"
  become: true
  #ansible.builtin.apt:
  ansible.builtin.package:
    state: absent
    name: "{{ item }}"
  with_items:
    - "{{ ansible_facts.packages }}"
