---

- name: Create configuration file
  template:
    src: "nodejs_pm2_ecosystem.json.j2"
    dest: "{{ steamengine_conf_path }}/nodejs_pm2_ecosystem.json"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rw,g=r,o=
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_nodejs

- name: "Download build {{ steamengine_build_url }}"
  get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ steamengine_build_checksum }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    headers: "{{ steamengine_build_url_headers }}"
    validate_certs: "{{ steamengine_build_url_validate_certs }}"
  notify:
    - "{{ steamengine_project_name }} restart"
  register: get_url_build
  tags:
    - steamengine_deploy_nodejs

- name: "Is there a new build: {{ get_url_build.changed }}"
  set_fact:
    new_build_to_deploy: get_url_build.changed
  tags:
    - steamengine_deploy_nodejs

- name: Create pm2 directory
  file:
    path: "{{ steamengine_project_root_path }}/pm2"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rwx,o=
    state: directory
  tags:
    - steamengine_deploy_nodejs

- name: Clean www directory
  file:
    path: "{{ steamengine_project_root_path_web }}"
    state: absent
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: Clean www directory (2)
  file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    state: directory
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: Update www directory
  unarchive:
    src: "{{ steamengine_project_root_path }}/project.zip"
    dest: "{{ steamengine_project_root_path_web }}"
    remote_src: true
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: "Add read permission for {{ steamengine_app_user }}"
  file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    recurse: true
    mode: u=rwx,g=rx,o=
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: "Add write permission for {{ steamengine_app_user }} on {{ steamengine_nodejs_allowed_write_paths }}"
  file:
    path: "{{ steamengine_project_root_path_web }}/{{ item }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    recurse: true
    mode: u=rwx,g=rwx,o=
  when: new_build_to_deploy
  loop: "{{ steamengine_nodejs_allowed_write_paths }}"
  tags:
    - steamengine_deploy_nodejs
