---

- name: Create configuration file
  ansible.builtin.template:
    src: "nodejs_pm2_ecosystem.json.j2"
    dest: "{{ steamengine_conf_path }}/nodejs_pm2_ecosystem.json"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rw,g=r,o=
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_deploy_nodejs

- name: "Download build {{ steamengine_build_url }}"
  ansible.builtin.get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ steamengine_build_checksum }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    headers: "{{ steamengine_build_url_headers }}"
    validate_certs: "{{ steamengine_build_url_validate_certs }}"
  notify:
    - "{{ steamengine_project_name }} restart"
  register: get_url_build
  tags:
    - steamengine_deploy_nodejs

- name: "Is there a new build: {{ get_url_build.changed }}"
  ansible.builtin.set_fact:
    new_build_to_deploy: "{{ get_url_build.changed }}"
  tags:
    - steamengine_deploy_nodejs

- include_tasks:
    file: common/pre_deploy.yml
    apply:
      tags:
        - steamengine_deploy_nodejs
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: Fix permissions before updating source
  ansible.builtin.command: "/{{ steamengine_home_path }}/bin/steamengine fixpermissions"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: Create pm2 directory
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path }}/pm2"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rwx,o=
    state: directory
  tags:
    - steamengine_deploy_nodejs

- name: Clean www directory
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    state: absent
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: Clean www directory (2)
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    state: directory
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: Update www directory
  ansible.builtin.unarchive:
    src: "{{ steamengine_project_root_path }}/project.zip"
    dest: "{{ steamengine_project_root_path_web }}"
    remote_src: true
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs

- name: Fix permissions after updating source
  ansible.builtin.command: "/{{ steamengine_home_path }}/bin/steamengine fixpermissions"
  when: new_build_to_deploy
  tags:
    - steamengine_deploy_nodejs
