---

- name: "Download build {{ steamengine_build_url }}"
  get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ steamengine_build_checksum }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  notify:
    - "{{ steamengine_project_name }} restart"
  register: get_url_build
  tags:
    - steamengine_deploy_nodejs

- name: Create pm2 directory
  file:
    path: "{{ steamengine_project_root_path }}/pm2"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rwx,o=
    state: directory
  tags:
    - steamengine_deploy_nodejs

- name: Clean www directory
  file:
    path: "{{ steamengine_project_root_path_web }}"
    state: absent
  when: get_url_build.changed
  tags:
    - steamengine_deploy_nodejs

- name: Clean www directory (2)
  file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    state: directory
  when: get_url_build.changed
  tags:
    - steamengine_deploy_nodejs

- name: Update www directory
  unarchive:
    src: "{{ steamengine_project_root_path }}/project.zip"
    dest: "{{ steamengine_project_root_path_web }}"
    remote_src: true
  when: get_url_build.changed
  tags:
    - steamengine_deploy_nodejs

- name: "Add read permission for {{ steamengine_app_user }}"
  file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    recurse: true
    mode: u=rwx,g=rx,o=
  tags:
    - steamengine_deploy_nodejs
